[package]
name = "auto_symlink"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
env_logger = { version = "0", features = ["color"] }
url = "2"
log = "0"
